name: mova
description: A streaming mobile app

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.7+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.3.2
  intl: any
  google_fonts: ^4.0.3
  logger: ^1.1.0
  flutter_animate: ^4.1.0
  dio: ^5.1.1
  rename: ^2.1.1
  audioplayers: ^4.0.1
  firebase_core: ^2.10.0
  animated_bottom_navigation_bar: ^1.1.0
  flutter_hooks: ^0.18.5+1
  auto_size_text: ^3.0.0
  hooks_riverpod: ^2.3.6
  freezed_annotation: ^2.1.0
  path_provider: ^2.0.14
  sembast: ^3.4.4
  rxdart: ^0.27.7
  path: ^1.8.2
  dartz: ^0.10.1
  auto_route: ^6.0.1
  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  cached_network_image: ^3.2.3
  another_flushbar: ^1.12.29
  readmore: ^2.1.0
  flutter_rating_bar: ^4.0.1
  youtube: ^1.0.1
  youtube_player_flutter: ^8.1.2
  equatable: ^2.0.5
  share_plus: ^7.0.0
  social_share: ^2.3.1
  flutter_easyloading: ^3.0.5
  material_floating_search_bar_2: ^0.5.0
  image_picker: ^0.8.7+5
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  flutter_progress_hud: ^2.0.2
  animations: ^2.0.7
  flutter_facebook_auth: ^5.0.11
  upgrader: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  freezed: ^2.3.2
  json_serializable: ^6.4.0
  auto_route_generator: ^6.2.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/sounds/sound-intro.mp3
