// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqTNgCrLfPIM5iI9aRfg1MtMoTVUI6Pk8',
    appId: '1:273807654254:web:6eee57fdea2ab82ddb957f',
    messagingSenderId: '273807654254',
    projectId: 'mova-9fd52',
    authDomain: 'mova-9fd52.firebaseapp.com',
    storageBucket: 'mova-9fd52.appspot.com',
    measurementId: 'G-DBRENQDKSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlJ-aZBwQbRs_tWHmZ5dEqkgespUMS98',
    appId: '1:273807654254:android:a08c2a8f068bb7f1db957f',
    messagingSenderId: '273807654254',
    projectId: 'mova-9fd52',
    storageBucket: 'mova-9fd52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPvhyB9tGOOSW7LbRRYyWKzkPi-8lxmo',
    appId: '1:273807654254:ios:f4f4294a00060499db957f',
    messagingSenderId: '273807654254',
    projectId: 'mova-9fd52',
    storageBucket: 'mova-9fd52.appspot.com',
    iosClientId: '273807654254-iso75m7rmfi3g24g46sa2mcbqraufm6q.apps.googleusercontent.com',
    iosBundleId: 'com.app.mova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPvhyB9tGOOSW7LbRRYyWKzkPi-8lxmo',
    appId: '1:273807654254:ios:f4f4294a00060499db957f',
    messagingSenderId: '273807654254',
    projectId: 'mova-9fd52',
    storageBucket: 'mova-9fd52.appspot.com',
    iosClientId: '273807654254-iso75m7rmfi3g24g46sa2mcbqraufm6q.apps.googleusercontent.com',
    iosBundleId: 'com.app.mova',
  );
}
