@baseUrl = https://api.themoviedb.org/3

@api_key = bcb184a317335ad93da00f543ab44f04

@movie_id = 502356
@review_id = 64440771cee2f667e736c55d

@page = 1

### GEt list of popular movies
GET {{baseUrl}}/movie/popular/?api_key={{api_key}}&page={{page}}

### GET list of top rated movies
GET {{baseUrl}}/movie/top_rated/?api_key={{api_key}}&page={{page}}
### Get movie [details]
GET {{baseUrl}}/movie/{{movie_id}}?api_key={{api_key}}

### Get [reviews]
GET  {{baseUrl}}/movie/{{movie_id}}/reviews?api_key={{api_key}}

### Get videos [related to a movies]
GET  {{baseUrl}}/movie/{{movie_id}}/videos?api_key={{api_key}}

### Get movie [reviews]
GET  {{baseUrl}}/movie/{{movie_id}}/reviews?api_key={{api_key}}

### Get [reviews details]
GET  {{baseUrl}}/review/{{review_id}}?api_key={{api_key}}
### Get [top rated] movies
GET {{baseUrl}}/movie/top_rated/?api_key={{api_key}}&page={{page}}

### Get [Up comming] movies
GET {{baseUrl}}/movie/upcoming/?api_key={{api_key}}&page={{page}}

### Get [Similar] movies
GET {{baseUrl}}/movie/{{movie_id}}/similar?api_key={{api_key}}
### GET [Search] Movies
GET {{baseUrl}}/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&without_keywords=John&api_key={{api_key}}