name: Test, build & deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean projet and get dependencies
        run: flutter clean && flutter pub get

      - name: Run test
        run: flutter test
