name: Test, build & deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Echo Test
        run: echo This\ is\ the\ firt\ job
