name: Test, build & deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean projet and get dependencies
        run: flutter clean && flutter pub get

      - name: Run test
        run: flutter test

  android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean projet and get dependencies
        run: flutter clean && flutter pub get

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build apk
        run: flutter build apk

      - name: Build appbundle
        run: flutter build appbundle

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: ${{ secrets.TESTERS_GROUPS }}
          file: build/app/outputs/flutter-apk/app-release.apk
